/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_TestJni */

#ifndef _Included_com_example_test_TestJni
#define _Included_com_example_test_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_TestJni
 * Method:    printJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_TestJni_printJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
